services:
  db:
    image: postgres:alpine
    container_name: sci-web-db
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - ./postgres-data:/var/lib/postgres/data
#  pgadmin:
#    image: 'dpage/pgadmin4:latest'
#    ports:
#        - '5050:80'
#    environment:
#      PGADMIN_DEFAULT_EMAIL: demo@example.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
#    depends_on:
#        - db
